# Permalinks
permalink:           pretty

# Setup
title:               JNYH
tagline:             Just Rather Moderate Okay Data Science Blog
url:                 http://jnyh.github.io
paginate:            2
baseurl:             ""

# Assets
#
# We specify the directory for Jekyll so we can use @imports.
sass:
  sass_dir:          _sass
  style:            :compressed

# About/contact
author:
  name:              James Ng
  url:               https://www.linkedin.com/in/james-ng-53332055/
  email:             jnyh@yahoo.com

# Custom vars
version:             2.0.0
github:
  repo:              https://github.com/jnyh

# Gems
gems:
  - jekyll-paginate
  - jekyll-gist

# Page List
pages_list:       
  About: '/about'
  Archive: '/archive'
  Feed: '/index.html'
